import type { Metadata, Viewport } from 'next'
import { Frank_Ruhl_Libre, Assistant } from 'next/font/google'
import './globals.css'

import GSAPInit from '@/components/GSAPInit'
import { WhatsAppFloat } from '@/components/WhatsAppFloat'
import JsonLd from '@/components/seo/JsonLd'
import { siteGraph, faqPageJsonLd } from '@/lib/schema'
import { SITE_URL } from '@/lib/site'

// Generated by design-system-generator — pasted from design/out/fonts.snippet.tsx.
// RTL default: the Hebrew face is the primary --font-display; a Latin-only
// display face (if any) is exposed separately and only paints Latin glyphs.
// שלושה משקלים לכל משפחה, וזה כל מה שהמערכת מגדירה: 400 · 500 · 600.
// קודם נטענו 8 (Frank 400/500/700, Assistant 300/400/500/600/700) ושימשו 3.
const fontFrankRuhlLibre = Frank_Ruhl_Libre({
  subsets: ['hebrew', 'latin'],
  weight: ['400', '500', '600'],
  variable: '--font-frank-ruhl-libre',
  display: 'swap',
})
const fontAssistant = Assistant({
  subsets: ['hebrew', 'latin'],
  weight: ['400', '500', '600'],
  variable: '--font-assistant',
  display: 'swap',
})

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
}

// Title/description are brand.json's (brand.name / brand.tagline); the rest is
// the seo agent's block, applied here because that agent does not own this file.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: 'ניקול בן מלך | רפואה סינית לנשים בתל אביב',
  description: 'רפואה סינית לנשים, בקליניקה בתל אביב. מתחילות באבחון, ומשם מטפלות בשורש.',
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    locale: 'he_IL',
    url: SITE_URL,
    siteName: 'ניקול בן מלך',
    title: 'ניקול בן מלך | רפואה סינית לנשים בתל אביב',
    description: 'רפואה סינית לנשים, בקליניקה בתל אביב. מתחילות באבחון, ומשם מטפלות בשורש.',
    // images לא מוגדר כאן בכוונה. src/app/opengraph-image.png מספק אותו
    // דרך קונבנציית הקבצים של Next, ואומת ב-HTML שנבנה: og:image,
    // og:image:width/height ו-twitter:image נפלטים אוטומטית עם hash
    // לשבירת קאש. הגדרה ידנית כאן היתה דורסת את זה ומאבדת את ה-hash.
    //
    // ⚠️ og:image:alt לא נפלט. src/app/opengraph-image.alt.txt קיים,
    // אבל בלוק ה-openGraph הזה מצל עליו. לא קריטי — תגית נגישות
    // לכרטיס השיתוף, לא לתצוגה עצמה.
  },
  twitter: {
    card: 'summary_large_image',
    title: 'ניקול בן מלך | רפואה סינית לנשים בתל אביב',
    description: 'רפואה סינית לנשים, בקליניקה בתל אביב. מתחילות באבחון, ומשם מטפלות בשורש.',
  },
  // NOINDEX UNTIL LAUNCH — deliberate. The real domain and WhatsApp number are
  // still placeholders (SITE_URL in src/lib/site.ts, WHATSAPP_PHONE in
  // src/lib/whatsapp.ts). Nothing goes to production or Search Console until
  // both are filled in. FLIP THIS TO index:true, follow:true AT LAUNCH,
  // together with src/app/robots.ts.
  robots: {
    index: false,
    follow: false,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="he"
      dir="rtl"
      className={`${fontFrankRuhlLibre.variable} ${fontAssistant.variable}`}
    >
      <body className="font-body antialiased">
        <GSAPInit />
        <JsonLd data={siteGraph} />
        <JsonLd data={faqPageJsonLd} />
        {children}
        {/* Mounted once, globally — every section's inline CTA is a separate
            <WhatsAppLeadButton />. */}
        <WhatsAppFloat />
      </body>
    </html>
  )
}
